# Generated by Django 3.1.4 on 2020-12-09 12:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='l_watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
